require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/setup'
    - 'vendor/**/*'

Metrics/ParameterLists:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/ExampleLength:
  Max: 50
RSpec/MultipleExpectations:
  Enabled: false
Layout/LineLength:
  Max: 150
